### ISSUE TITLE
Move Extensions to fretwork

### ISSUE THREAD

**Issue by Linkid** [fofix/fofix#128]
Moving all C files to fretwork could help to release fofix because it will be python code only.

**Comment by Linkid** [comment]
The `VideoPlayer` extension is importing some FoFiX classes (`fofix.core.View.BackgroundLayer` and `fofix.core.Input.KeyListener`).

**Comment by mdsitton** [comment]
Yeah that was my original plan for fretwork

**Comment by Linkid** [comment]
First, I've just put extension in their own repo:
- [ ] pypitch: https://github.com/fofix/python-pypitch
- [ ] cmgl: https://github.com/fofix/python-cmgl
- [ ] videoplayer

**Comment by Linkid** [comment]
All extensions are removed from this repo and live into their own repo.
