### ISSUE TITLE
Could not find required program "pkg-config".

### ISSUE THREAD

**Issue by wrzwicky** [fofix/fofix#147]
On Windows 10, with plain Windows version of Python 2.7, doing the "pip install -r requirements.txt" for FoFiX yields this message:
```
Collecting fretwork==0.3.0 (from -r requirements.txt (line 10))
  Using cached fretwork-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    checking for program pkg-config... not found
    Could not find required program "pkg-config".
    (Check that you have the latest version of the dependency pack installed.)
```
This was not a requirement in the past, and probably should not be a requirement now, as installing pkg-config on Windows appears to be a nightmare.  But if we need it now, then requirements.txt needs to be updated.

Workaround: Fretwork installs cleanly from the pre-built binaries at https://github.com/fofix/fretwork/releases/tag/0.3.0

Since people set up to code FoFiX only need Python and may not have the native compiler to build Fretwork, FoFiX should only pull pre-built binaries.

**Comment by Linkid** [comment]
Hi! Thank your for this issue.
It seems I forgot to upload windows wheels on pypi… So, pip downloads sources and try to launch the install manually, which required `pkg-config`.
