### ISSUE TITLE
Fofix crash when the song is to be played

### ISSUE THREAD

**Issue by fervi** [fofix/fofix#164]
Perhaps something with my system (I tried to reinstall FoFiX a few times and nothing) - a bug in the library or something.

In general, notes are flying, there is a countdown of 3, 2, 1 ... and when the song is about to start is a crash program.

https://pastebin.com/gVTRwA39

**Comment by fervi** [comment]
War of Freedom (?) from Sectoid
https://packages.debian.org/buster/fretsonfire-songs-sectoid

It works on Frets on Fire and it and once worked with Fofix. I think this is a bug with some library (hmm ...)

**Comment by fervi** [comment]
Something with my HOME profile, on other user works :P

**Comment by Linkid** [comment]
Ok, cool :).
