### ISSUE TITLE
FoFiX specific Python distribution and environment management

### ISSUE THREAD

**Issue by shnewto** [fofix/fofix#207]
Hi there :wave:

I've been talking through a lot of what follows with @Linkid in the #fofix channel on the OFTC IRC. That conversation is at a point where brining this up as an issue will probably benefit that dialog, minimally it'll be a convenient place to provide artifacts and view changes anyone can look at. For everyone's sake, I'll reiterate the gist of those conversations here.

Ultimately I'd like to start putting together a FoFiX specific Python distribution (free, fully open-source-licensed, and redistributable) with the goal of making it really easy FoFiX developers and users to get up and running. But I'm interested in getting an official go-ahead before really digging into anything (or a "no thanks!" if that ends up being the case 😄)

For the broad picture, I'm working on an initiative at ActiveState to try and contribute meaningfully to open source projects that have complicated dependencies, as well as those with challenges around portability and environment compatibility. We think FoFiX is an ideal candidate for one of our pilots to showcase how we can help, and what it all looks like. 

Now for some actual details haha.

(Note: I've been using the words 'runtime' and 'distribution' pretty much interchangeably in conversations around what we're working on. I realize now that it might be clearer if I settled on 'distribution' when talking about Python specifically. I'll try and do that here.)

First off, if you're familiar with other Python distributions like ActivePython or Anaconda, the FoFiX specific distribution would be along those lines. Where ActivePython and Anaconda come pre-bundled with a broad range of packages, from Jupyter and SciPy, to docopt and pep8, the FoFiX distribution would be bundled with just the requirements of this project (like PyAudio, PyOpenGL, and fretwork). You can think of it as a sort of alternative to `pip install everything-I-need-to-work-or-use-on-fofix`, except that any errors that could occur to cause pip to fail mid-install have been tested and resolved before you get to it. And it doesn’t care what you’ve pip installed before.

The work of keeping things distinct between your regular environment, and your project's, is handled by our state tool. Like a Python virtualenv, it isolates the project's artifacts so there's no need to install the distribution the system level. It does other cool things too though like letting you isolate scripts from the parent environment as well.

### From the CLI
**The first time:**
1. Install the state tool
2. Run `state activate` from inside this project
3. Log-in on the command line with ActiveState platform credentials, or authenticate using GitHub credentials

**The rest of the time:**
1. Run `state activate` from inside this project

## From the ActiveState platform
1. Log-in to the ActiveState platform.
2. Download the FoFiX Python distribution.
3. Install FoFiX Python distribution on your system.

## What this would look like for FoFiX:
1. An activestate.yaml added to the FoFiX repository that specifies the link to the project on the platform and the project distribution's language, Python.
2. A reference in the FoFiX 'Setup' documentation that lists the ActiveState solution as an alternative to the existing steps for getting up and running.

(**Note on step 2**. There is no expectation that our solution will supplant or replace any other recommendations on getting started, now or going forward. We'd just love it to be one of the options listed.)

### Developers v Users
While our distributions target the developer, there's no reason they couldn't provide a similar benefit to FoFiX users. We could even put together a couple distributions (something like FoFiX-dev and FoFiX) to account for differences between what a user needs to get started, and what a developer would.

### Containers
Container technology like Docker and VirtualBox offer things that may seem similar at first glance (notably, environment management). They differ though, in that containers (as I think of them) are something that exist distinct and isolated from whatever’s running them. An ActiveState distribution and its environment exists as a stand alone _within_ the system that runs it. So as a basic example, if I installed a FoFiX specific ActiveState distribution for my OS and architecture, I could just start in, developing and running FoFiX in the same environment the rest of my day to day computer exists in, with all its aliases, editors, scripts, music players, browsers, etc.

### CI/CD
CI/CD hasn't been our most targeted use case, but it's certainly a place an ActiveState distribution could represent some simplifications. In the FoFiX `.travis.yml` file for instance, the existing `before_install:` section and most of `install:` could be replaced by one step to install a pre-built distribution for the target platform.

### Licensing
Traditionally, ActiveState distributions have been bundled with a custom license that reflects its long history of working most directly with Enterprise customers (rather than open source communities). What we’re proposing here though are distributions that would be fully open source. We’re in the process of our transition from that historic licensing approach, to a community minded one, so any feedback or insight here would be really valuable.

## Next steps
If any of this is something that this project is willing to entertain, I'd love to get started building one of these distributions and offer it up for a test drive to see if it seems feels like something y'all actually do find helpful.

I'm happy to address any questions or concerns here as well, thanks!

**Comment by shnewto** [comment]
Hey there @Linkid and the rest of the FoFiX community 👋 

Thought you were overdue for some updates on where ActiveState is at regarding something helpful you y'all you could test drive.  Nothing to share yet, we're still overcoming some of the challenges of the packages that would provide the most value for this project, namely the OpenGL things 😄

Mostly I just wanted to let y'all know we haven't forgotten the our conversations or this issue. We're still excited to provide something really helpful when we can, but we're still working. 

Thanks for all the awesome work you do, and for your patience.

**Comment by Linkid** [comment]
Hi @shnewto.
I'll be happy to have some updates about your project. It could be great to test it and to see how it goes.
On my side, I'm still working on the deployment, to release easily.

**Comment by shnewto** [comment]
👋 Hi @Linkid :)  

I'm no longer on the team that's working on this project but I imagine @rawktron or @zakgreant may be able to fill in the state of things for you. 

Best wishes!

**Comment by shnewto** [comment]
wowie, this has been sitting for quite a while, I've long moved on from ActiveState and it doesn't seem like anyone from over there is picking up the torch so I'm going to close this one. thanks for your patience.
