### ISSUE TITLE
[GIT] invalid literal for int() with base 10: 'dev0'

### ISSUE THREAD

**Issue by IntinteDAO** [fofix/fofix#239]
**Describe the bug**
The code crashing on startup

**Error message**
fofix-git                               
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "./FoFiX.py", line 157, in <module>
    version = tuple([int(i) for i in version.split('.')])
ValueError: invalid literal for int() with base 10: 'dev0'

**To Reproduce**
Just run fofix-git on Arch Linux :P

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 2.7.18

**Comment by Linkid** [comment]
Thanks for this issue :).
The version of fretwork doesn't seem to be compatible with semver (`1.0.dev0` instead of `1.0-dev0`), and the fofix code is not flexible enough.
