### ISSUE TITLE
Determine what we should do with pygame.

### ISSUE THREAD

**Issue by mdsitton** [fofix/fofix#29]
Currently pygame hasn't had a 'stable' release since August 2009 (for comparison FoFiX 3.121 was released December 2009).

I don't think the project is completely dead, but considering they are advertising new releases of PySDL2 in the news feed on their website....

We have been wanting to move up to python 3.x however there are currently some issues with this. Right now most distro's do not have pygame packaged for python 3. I'm guessing the current stable release has some incompatibility with newer python versions, but who knows. 

We can still get mostly up-to-date development versions for windows from: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame

PySDL2 uses ctypes, and seems like it would be a good fit since the audio stuff could stay as it is now.

EDIT:
So i went through and edited it removed some inaccuracies about PySDL2.

I think we should definitely look into moving over to it because it would give us more control. We could also probably get rid of the dependency on pywin32 since i think we mainly use it for going around pygame bugs on windows.

**Comment by Linkid** [comment]
Pygame development started again this year with pygame 1.9.3. This should do the trick for now.
