### ISSUE TITLE
A potential way forward...

### ISSUE THREAD

**Issue by mdsitton** [fofix/fofix#30]
So I've been thinking a lot about what we should do to move this project forward.

So i'm thinking we need to define a very basic set of features. Take all code that doesn't pertain to them and throw it out.

With the simpler code base start cleaning up general architecture of the game, replace dependencies, and work for python 3 compatibility. Once we get a good solid clean base then we can start adding some features back.

I mean its been 4 1/2 years since a 'stable' release and i think its time for a bit more drastic measures.

Thoughts?

**Comment by mdsitton** [comment]
I ended up taking this idea to a bit of an extreme. So far i have removed 19543 lines of code according to git. Currently I have basically taken the game down to a super basic level here is a small list of some of the stuff i've removed.

* multiplayer
* solo's
* starpower/overdrive
* RockMeter
* Scoring
* Song Results screen
* Basically removed the lobby, its still there but is just press enter to continue.
* player profiles(also in the process broke the ability to get to drums)
* vocals
* Cleaned up the settings menu
* Jurgen
* Removed lots of code from the setlist.
* Started to clean up the note hit detection code.
* Found the source of the stuttering in the track rendering
  * The cause is from using the time from the audio playing code to render everything. I have a workaround in place for now which makes things so much smoother.
* Fully migrated the game to use the TempoTrack, removing all tempo events from the notes track.
* Removed all gamemodes.
* Ended up removing a lot of theming in the process.
* Controller support(Mainly to try to simplify the input system a bit).
There are some other changes that i haven't mentioned as well.

The in-game performance is a lot better as well. On an old low end atom based system i have, the game went from the game frozen not able to be played to 30 fps. My desktop went from around 100 to 500, with a heavy amount of notes, without a lot of notes the framerate at max was around 900.

**Comment by mdsitton** [comment]
Forgot to mention this but if anyone want to take a look at the branch so far.
https://github.com/mdsitton/fofix/tree/feature-cleaning

**Comment by Salamandar** [comment]
Hi there !

I spoke a bit with a "python master" about FoF, and when I told him about it using PIL, he laughed about it.

Seems like Pillow is a great fork, maintained, cross-platform, etc etc.

It would be better to use it, right ?
I don't think it would be much work to use it, as it is a fork of PIL.

**Comment by mdsitton** [comment]
Technically pillow is backwards compatible with PIL for the most part, and when im running locally i always install pillow... We just haven't had a release since pillow has been a thing, and we have yet to update the building instructions about that.

**Comment by mdsitton** [comment]
so in short i agree :P

**Comment by Salamandar** [comment]
Great :D

**Comment by Linkid** [comment]
I'm closing this issue 'cause it is too big to end up in only one issue (and some ideas was merged, like bumping dependancies).
