### ISSUE TITLE
no songs!!!

### ISSUE THREAD

**Issue by brothermechanic** [fofix/fofix#37]
Hello
I want to play fofix, 
but no sound  http://wstaw.org/m/2015/09/11/plasma-desktopwb4441.png
i installed in this way
1) install all deps
2) git clone https://github.com/fofix/fofix.git
3) cd /media/var/bin/fofix
4) python2 setup.py build_ext --inplace --force
5) python2 ./FoFiX.py

This is output
$ python2 ./FoFiX.py
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:963:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Please help!

**Comment by brothermechanic** [comment]
There is typo - no SONGS (soud works fine)

**Comment by mdsitton** [comment]
We don't provide any songs with the game. However, I would like to try and change this going into the future.
