### ISSUE TITLE
crash on start playing

### ISSUE THREAD

**Issue by brothermechanic** [fofix/fofix#38]
Hello
I'm new user
I download songs from http://kent.dl.sourceforge.net/project/fretsonfiresps/Song%20Pack.rar
Copy it to /opt/fofix/data/songs (and to /home/bm/.fofix/songs/ , because fofix crash)
Run game and set path to songs
Fofix found songs
When i select any song and set level (for ex easy) and start game - fofix is crashing
/home/bm/.fofix/fofix.log https://bpaste.net/show/a57e3abce699
log from console http://paste.org.ru/?07v7qb

**Comment by mdsitton** [comment]
Are you using any specific language other than english within the game?

And also are you using FoFiX 4.0 Alpha 2 or is it a version pulled from git?

**Comment by mdsitton** [comment]
Tell me
