### ISSUE TITLE
Make FretWork working in a package/dependencies management system (well… any linux distro :p )

### ISSUE THREAD

**Issue by Salamandar** [fofix/fofix#43]
Well, basically, I'm using Manjaro (Arch-based), and there is already a fofix package (https://aur.archlinux.org/packages/fofix-git, build from git clone of this repo).

What would be best : 
- Create another package (so as dependency of fofix and fof) of FretWork
- clone fofix and fretwork, then bind them together as an only package
- Add fretwork as a git submodule inside the fofix repo. That would lead to an only package

I can create the package for AUR, that's something I already did. But YOU know how you created fretwork so what would be best.

**Comment by nhydock** [comment]
I vote for the git submodule approach

**Comment by Salamandar** [comment]
Yeah I would agree with that !

**Comment by mdsitton** [comment]
Fretwork should work with pip as it is(a sort of package manager), I have precompiled wheels for windows. On linux you can just install from the source package with pip (should work on osx as well with xcode installed). Plus when we finish getting virtualenv setup all of this should be simplified.
@stump finish that please :)

I don't really like git submodules to much, I always forget to update them, and to run the extra command when cloning...

**Comment by Salamandar** [comment]
Hum… Well we could create a fretwork AUR package that would install itself inside python2/site-packages (just like with pip). Here is an example with python-cerealizer : 

    # Maintainer: Aaron DeVore <aaron.devore@gmail.com>
    # Contributor: rayte <rabyte__gmail>
    # Contributor: aldeano <aldea.diaguita at gmail.com>

    pkgname=(python-cerealizer python2-cerealizer)
    pkgver=0.8.1
    pkgrel=2
    pkgdesc="A Python module for saving objects in a file"
    arch=('any')
    url="http://home.gna.org/oomadness/en/cerealizer/"
    license=('PSF')
    source=(https://pypi.python.org/packages/source/C/Cerealizer/Cerealizer-${pkgver}.tar.bz2)
    md5sums=('a77b6215f77c539035ae46a73bfa819e')

    package_python-cerealizer() {
      cd "$srcdir/Cerealizer-$pkgver"
      depends=('python')
      
      python setup.py install --root="$pkgdir"
    }

    package_python2-cerealizer() {
      cd "$srcdir/Cerealizer-$pkgver"
      depends=('python2')
      
      python2 setup.py install --root="$pkgdir"
    }

That allows to use the system package manager.

**Comment by Salamandar** [comment]
https://aur.archlinux.org/packages/python2-fretwork-git
Well, this is done and works well.

**Comment by mdsitton** [comment]
Yeah that would work for those of us that use arch. Only gripe is that i was planning on using the "released" versions for the games and then making major changes on master and updating things when i put a new release out.

**Comment by Salamandar** [comment]
Well the AUR package can track a specified branch, like a "release" one.
It can also use release archives, but that needs to update the AUR package each time you release a new version.

**Comment by mdsitton** [comment]
true
