### ISSUE TITLE
Custom Drum's Fret Buttons glitches

### ISSUE THREAD

**Issue by arielenter** [fofix/fofix#49]
Hello again :)

I think this will be my last bug report :P for 4 alpha 2

The only theme I have found so far for for fofix 4 alpha 2 is this one:
http://www.fretsonfire.net/forums/viewtopic.php?f=17&t=54270&sid=2cda1bb617fa405acec1b66ede33563f

This theme has the following very cool Custom Drum's Fret Buttons:

http://postimg.org/image/huii9tlil/

Unfortunately using them with alpha 2 is not working right, and I'm pretty sure is not the theme's fault.

When ever I try to use the Custom Drum's Fret Buttons, each time I hit any of the frets the right next fret also lights up. For instance hitting fret one also lights up fret two. Also, while hitting frets 4, the bass drum also appears hit. This is only in appearance since they won't actually count as hit in the game.

Hope I was able to explain my self right. If needed you could test what I'm talking about by downloading the Custom Drum's Fret Buttons from my link and putting it on frets/drum/fretbuttons.png of any theme . 

Thank you very much.

**Comment by arielenter** [comment]
Also I want to mention that not having a special custom drum's frets (frets/drum/fretbuttons.png) and just using the regular ones use by the guitars for instant (frets/fretbuttons.png) they work fine. It's just the onces made specifically for the drums (frets/drum/fretbuttons.png) which have this problem.

**Comment by mdsitton** [comment]
Yeah that would be my old theme .I haven't seen this issue myself, though i don't play that drums often. Are you able to make a video or take some screenshots?

**Comment by arielenter** [comment]
Trying to run the latest master I get the following error:

Traceback (most recent call last):
  File "/home/ariel/Escritorio/fofix/fofix-master/FoFiX.py", line 156, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/home/ariel/Escritorio/fofix/fofix-master/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
ImportError: No module named _VideoPlayer

Any clue?

**Comment by mdsitton** [comment]
Make sure you have ran `python setup.py build_ext --in place --force` because you need to make sure the C extension modules are compiled.

**Comment by arielenter** [comment]
Thanks. I'm sorry, it has passed some time since I last compiled the game. Thank you for your patience.

I upload this video:
https://goblinrefuge.com/mediagoblin/u/arielenter/m/fofix-alpha-2-problem/

In it, you can see that every time fret1 is pressed fret2 lights up as well. Same happens with frets 2 with 3 and so on. Even when you press fret4 the bass lights up, and pressing the bass lights up fret1.

I downloaded the mentioned theme again from scratch, and using the default or custom key mapping for the Drums doesn't make a difference. I'm using the default options values. Hope this helps.

**Comment by wrzwicky** [comment]
Verified as of today.

1. Set up a single player with Default Drums.
1. Quickplay "Eye of the Tiger" from Rock Band 2.
1. Play along; drum keys on keyboard activate the correct drum along with the drum to the right.

Also, sounds are inverted -- music plays if you miss the note, and is suppressed if you hit it.

**Comment by wrzwicky** [comment]
Fixed in #96. Note that theme itself needs to be updated.
