### ISSUE TITLE
Github build LNK1181 error (Windows 10 Home)

### ISSUE THREAD

**Issue by FILTUT** [fofix/fofix#56]
Whenever i do "python setup.py build_ext --inplace --force" it sends an error
command 'C:\\Users\\aPoC\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181

The entire command line

Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Filip>d:

D:\>cd "Frets On Fire X"

D:\Frets On Fire X>cd src

D:\Frets On Fire X\src>cd fofix

D:\Frets On Fire X\src\fofix>python setup.py build_ext --inplace --force
checking for program pkg-config... .\win32\deps\bin\pkg-config.exe
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
running build_ext
cythoning fofix/core/cmgl/cmgl.pyx to fofix/core/cmgl\cmgl.c
building 'fofix.lib.cmgl' extension
creating build
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\fofix
creating build\temp.win32-2.7\Release\fofix\core
creating build\temp.win32-2.7\Release\fofix\core\cmgl
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-ID:\Frets On Fire X\python\lib\site-packages\numpy\core\include" "-ID:\Frets On Fire X\python\include" "-ID:\Frets On Fire X\python\PC" -I.\win32\deps\include\msinttypes /Tcfofix/core/cmgl\cmgl.c /Fobuild\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj /EHsc
cmgl.c
d:\frets on fire x\python\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:D:\Frets On Fire X\python\libs" "/LIBPATH:D:\Frets On Fire X\python\PCbuild" opengl32.lib /EXPORT:initcmgl build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj "/OUT:D:\Frets On Fire X\src\fofix\fofix\lib\cmgl.pyd" /IMPLIB:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib and object build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.exp
cythoning fofix/core/pypitch/_pypitch.pyx to fofix/core/pypitch\_pypitch.cpp
building 'fofix.lib._pypitch' extension
creating build\temp.win32-2.7\Release\fofix\core\pypitch
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-ID:\Frets On Fire X\python\include" "-ID:\Frets On Fire X\python\PC" -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch\_pypitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj /EHsc
_pypitch.cpp
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-ID:\Frets On Fire X\python\include" "-ID:\Frets On Fire X\python\PC" -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch/pitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj /EHsc
pitch.cpp
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:D:\Frets On Fire X\python\libs" "/LIBPATH:D:\Frets On Fire X\python\PCbuild" /EXPORT:init_pypitch build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj build\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj "/OUT:D:\Frets On Fire X\src\fofix\fofix\lib\_pypitch.pyd" /IMPLIB:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib and object build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.exp
cythoning fofix/core/VideoPlayer/_VideoPlayer.pyx to fofix/core/VideoPlayer\_VideoPlayer.c
building 'fofix.lib._VideoPlayer' extension
creating build\temp.win32-2.7\Release\fofix\core\VideoPlayer
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline "-ID:/Frets On Fire X/src/fofix/win32/deps/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include/glib-2.0" "-ID:/Frets On Fire X/src/fofix/win32/deps/lib/glib-2.0/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include" -I. "-ID:\Frets On Fire X\python\include" "-ID:\Frets On Fire X\python\PC" -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer\_VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj /EHsc
_VideoPlayer.c
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline "-ID:/Frets On Fire X/src/fofix/win32/deps/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include/glib-2.0" "-ID:/Frets On Fire X/src/fofix/win32/deps/lib/glib-2.0/include" "-ID:/Frets On Fire X/src/fofix/win32/deps/include" -I. "-ID:\Frets On Fire X\python\include" "-ID:\Frets On Fire X\python\PC" -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer/VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /EHsc
VideoPlayer.c
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:D:/Frets On Fire X/src/fofix/win32/deps/lib" "/LIBPATH:D:/Frets On Fire X/src/fofix/win32/deps/lib" "/LIBPATH:D:/Frets On Fire X/src/fofix/win32/deps/lib" "/LIBPATH:D:/Frets On Fire X/src/fofix/win32/deps/lib" "/LIBPATH:D:\Frets On Fire X\python\libs" "/LIBPATH:D:\Frets On Fire X\python\PCbuild" opengl32.lib ogg.lib theoradec.lib ogg.lib glib-2.0.lib intl.lib swscale.lib /EXPORT:init_VideoPlayer build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj build\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj "/OUT:D:\Frets On Fire X\src\fofix\fofix\lib\_VideoPlayer.pyd" /IMPLIB:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.pyd.manifest
LINK : fatal error LNK1181: cannot open input file 'ogg.lib'
error: command 'C:\\Users\\Filip\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181

D:\Frets On Fire X\src\fofix>

**Comment by mdsitton** [comment]
Try moving your fofix folder to a location that doesn't have any spaces in its path.

So instead of D:/Frets On Fire/src/fofix try D:/fof/src/fofix or similar.

**Comment by FILTUT** [comment]
Tried moving the fofix folder to a no space path,and still gives me the LNK1181 error

Command Prompt


D:\fofix\src\fofix>python setup.py build_ext --inplace --force
checking for program pkg-config... .\win32\deps\bin\pkg-config.exe
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
running build_ext
cythoning fofix/core/cmgl/cmgl.pyx to fofix/core/cmgl\cmgl.c
building 'fofix.lib.cmgl' extension
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -ID:\Python27\lib\site-packages\numpy\core\include -ID:\Python27\include -ID:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/cmgl\cmgl.c /Fobuild\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj /EHsc
cmgl.c
d:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:D:\Python27\libs /LIBPATH:D:\Python27\PCbuild opengl32.lib /EXPORT:initcmgl build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj /OUT:D:\fofix\src\fofix\fofix\lib\cmgl.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib and object build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.exp
cythoning fofix/core/pypitch/_pypitch.pyx to fofix/core/pypitch\_pypitch.cpp
building 'fofix.lib._pypitch' extension
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -ID:\Python27\include -ID:\Python27\PC -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch\_pypitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj /EHsc
_pypitch.cpp
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -ID:\Python27\include -ID:\Python27\PC -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch/pitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj /EHsc
pitch.cpp
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:D:\Python27\libs /LIBPATH:D:\Python27\PCbuild /EXPORT:init_pypitch build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj build\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj /OUT:D:\fofix\src\fofix\fofix\lib\_pypitch.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib and object build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.exp
cythoning fofix/core/VideoPlayer/_VideoPlayer.pyx to fofix/core/VideoPlayer\_VideoPlayer.c
building 'fofix.lib._VideoPlayer' extension
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -ID:/fofix/src/fofix/win32/deps/include -ID:/fofix/src/fofix/win32/deps/include -ID:/fofix/src/fofix/win32/deps/include/glib-2.0 -ID:/fofix/src/fofix/win32/deps/lib/glib-2.0/include -ID:/fofix/src/fofix/win32/deps/include -I. -ID:\Python27\include -ID:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer\_VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj /EHsc
_VideoPlayer.c
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -ID:/fofix/src/fofix/win32/deps/include -ID:/fofix/src/fofix/win32/deps/include -ID:/fofix/src/fofix/win32/deps/include/glib-2.0 -ID:/fofix/src/fofix/win32/deps/lib/glib-2.0/include -ID:/fofix/src/fofix/win32/deps/include -I. -ID:\Python27\include -ID:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer/VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /EHsc
VideoPlayer.c
C:\Users\Filip\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:D:/fofix/src/fofix/win32/deps/lib /LIBPATH:D:/fofix/src/fofix/win32/deps/lib /LIBPATH:D:/fofix/src/fofix/win32/deps/lib /LIBPATH:D:/fofix/src/fofix/win32/deps/lib /LIBPATH:D:\Python27\libs /LIBPATH:D:\Python27\PCbuild opengl32.lib ogg.lib theoradec.lib ogg.lib glib-2.0.lib intl.lib swscale.lib /EXPORT:init_VideoPlayer build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj build\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /OUT:D:\fofix\src\fofix\fofix\lib\_VideoPlayer.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.pyd.manifest
LINK : fatal error LNK1181: cannot open input file 'ogg.lib'
error: command 'C:\\Users\\Filip\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181

**Comment by mdsitton** [comment]
What version of python do you have installed?

**Comment by wwizz** [comment]
Same issue here, python 32 bit

**Comment by fculpo** [comment]
Related to #48 i guess

**Comment by mdsitton** [comment]
Not sure, because I'm not having any issues on Windows myself.

**Comment by fculpo** [comment]
Depends if you are running form C: or another drive, that was my exact issue.

**Comment by mdsitton** [comment]
It also looks like his python install is also on the other drive as well.

**Comment by danielfariati** [comment]
I'm having the same problem.
Both fofix and python are installed in the D: drive.

**Comment by mdsitton** [comment]
Does it work if you install python on your C: drive?

**Comment by mdsitton** [comment]
I wonder if it could be an issue with the dependency pack... Its been needing an update...

**Comment by danielfariati** [comment]
I'm reinstalling python on my C: drive.
I'll keep you informed if it works or not.

**Comment by danielfariati** [comment]
It didn't :/

The same error occours:
```bash
LINK : fatal error LNK1181: cannot open input file 'ogg.lib'
error: command 'C:\\Users\\Daniel\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181
```

I tried:
With Python and Fofix on the D: drive
With Python and Fofix on the D: drive
With Fofix on the C: drive and Python on the D: drive
With Python on the C: drive and Fofix on the D: drive

The tests were made with python 2.7.10 with all the dependencies installed (including optional).

**Comment by mdsitton** [comment]
One more thing do you have the dependency pack put in the correct place?

**Comment by danielfariati** [comment]
Yep.
C:\fofix\win32 (with the deps folder).

**Comment by mdsitton** [comment]
I really dont understand why its not working for so many only difference from the original reporter is I'm on Windows 10 Pro instead.
```
C:\Users\Matthew\development\fofix>setup.py build_ext --inplace --force
checking for program pkg-config... .\win32\deps\bin\pkg-config.exe
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
running build_ext
cythoning fofix/core/cmgl/cmgl.pyx to fofix/core/cmgl\cmgl.c
building 'fofix.lib.cmgl' extension
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/cmgl\cmgl.c /Fobuild\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj /EHsc
cmgl.c
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild opengl32.lib /EXPORT:initcmgl build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.obj /OUT:C:\Users\Matthew\development\fofix\fofix\lib\cmgl.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.lib and object build\temp.win32-2.7\Release\fofix/core/cmgl\cmgl.exp
cythoning fofix/core/pypitch/_pypitch.pyx to fofix/core/pypitch\_pypitch.cpp
building 'fofix.lib._pypitch' extension
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch\_pypitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj /EHsc
_pypitch.cpp
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC -I.\win32\deps\include\msinttypes /Tpfofix/core/pypitch/pitch.cpp /Fobuild\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj /EHsc
pitch.cpp
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild /EXPORT:init_pypitch build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.obj build\temp.win32-2.7\Release\fofix/core/pypitch/pitch.obj /OUT:C:\Users\Matthew\development\fofix\fofix\lib\_pypitch.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.lib and object build\temp.win32-2.7\Release\fofix/core/pypitch\_pypitch.exp
cythoning fofix/core/VideoPlayer/_VideoPlayer.pyx to fofix/core/VideoPlayer\_VideoPlayer.c
building 'fofix.lib._VideoPlayer' extension
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -IC:/Users/Matthew/development/fofix/win32/deps/include -IC:/Users/Matthew/development/fofix/win32/deps/include -IC:/Users/Matthew/development/fofix/win32/deps/include/glib-2.0 -IC:/Users/Matthew/development/fofix/win32/deps/lib/glib-2.0/include -IC:/Users/Matthew/development/fofix/win32/deps/include -I. -IC:\Python27\include -IC:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer\_VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj /EHsc
_VideoPlayer.c
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -IC:/Users/Matthew/development/fofix/win32/deps/include -IC:/Users/Matthew/development/fofix/win32/deps/include -IC:/Users/Matthew/development/fofix/win32/deps/include/glib-2.0 -IC:/Users/Matthew/development/fofix/win32/deps/lib/glib-2.0/include -IC:/Users/Matthew/development/fofix/win32/deps/include -I. -IC:\Python27\include -IC:\Python27\PC -I.\win32\deps\include\msinttypes /Tcfofix/core/VideoPlayer/VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /EHsc
VideoPlayer.c
C:\Users\Matthew\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:/Users/Matthew/development/fofix/win32/deps/lib /LIBPATH:C:/Users/Matthew/development/fofix/win32/deps/lib /LIBPATH:C:/Users/Matthew/development/fofix/win32/deps/lib /LIBPATH:C:/Users/Matthew/development/fofix/win32/deps/lib /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild opengl32.lib ogg.lib theoradec.lib ogg.lib glib-2.0.lib intl.lib swscale.lib /EXPORT:init_VideoPlayer build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.obj build\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /OUT:C:\Users\Matthew\development\fofix\fofix\lib\_VideoPlayer.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib and object build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.exp

C:\Users\Matthew\development\fofix>
```

**Comment by danielfariati** [comment]
I have the exact same version of python.
Are you using this dependency pack: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/fofix/fofix-win32-deppack-20130304.zip?

**Comment by mdsitton** [comment]
try pulling, and see if there is any change.

**Comment by mdsitton** [comment]
Also yeah that is the same one.

**Comment by danielfariati** [comment]
Unfortunately, it didn't :/

**Comment by danielfariati** [comment]
I looked for the file "ogg.lib" in my computer and I don't have it anywhere.
Is the file generated in the setup process? Can this be what is causing the error?

**Comment by mdsitton** [comment]
it should be located in win32\deps\lib\ogg.lib

**Comment by mdsitton** [comment]
hmm odd... my copy of the dep pack has the lib file in it where as the downloaded one doesn't.

**Comment by mdsitton** [comment]
Well here is the version i have locally and it certainly works, using the downloaded deps pack i get the same issue.
https://dl.dropboxusercontent.com/u/37405488/fofix-win32-deppack-20130304-updated.zip

**Comment by danielfariati** [comment]
Yep! Now it worked.

**Comment by danielfariati** [comment]
But now there's another (probably unrelated) error.
When trying to run `python Fofix.py`, this error is thrown:
```
Traceback (most recent call last):
  File "FoFiX.py", line 143, in <module>
    if getattr(fretwork, '__version__'): # The first version of fretwork didnt have __version__
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by mdsitton** [comment]
Install the new version of fretwork, you did uncover a slight bug though.

**Comment by mdsitton** [comment]
That bug should now be fixed, and it should give you a more helpful error message instead.

**Comment by danielfariati** [comment]
Nice! It worked.
Thanks for the quick responses!

**Comment by mdsitton** [comment]
No problem, I'm going to close this issue now.

Also to summarize there was a dependency pack issue, so re-download it from the link in the readme then replace the old one and it should work.
