### ISSUE TITLE
How to play the game on windows 10?

### ISSUE THREAD

**Issue by mrknife00** [fofix/fofix#60]
I don't know if it is the right place to ask that, but, how to play the game on windows 10 64 bits?

**Comment by mdsitton** [comment]
Are you talking about FoFiX 3.121 or how to run FoFiX 4.0 from source?

**Comment by mrknife00** [comment]
In any fofix version, because no version ran on my Windows 10 64-bit

I just wanna play any version of the game on windows 10 64-bit

sorry my bad english!

**Comment by mdsitton** [comment]
Well i haven't seen any other issues so far running it on windows 10 64-bit. So some more info like your fofix log file would be helpful.

**Comment by mrknife00** [comment]
The game simply does not run, the Windows 10 is incompatible, does not create a log file... There's a way to run the game on Windows 10? Could be any version... That's all I want to know. Thanks

**Comment by mdsitton** [comment]
It always creates a log. Its in your appdata folder
you can type this in File Explorer to bring you there:
%appdata%\fofix

**Comment by mrknife00** [comment]
I didn't take a screenshot beacause the screen stay black... the screen stay black and nothing happens but I can hear the audio. If I click with the mouse button the game stops working, and its all!
Here the log:

[audio]
bits = 16
buffersize = 2048
crowd_volume = 0.8
delay = 100
disable_preview = True
enable_crowd_tracks = 1
frequency = 44100
guitarvol = 1.0
kill_volume = 0.0
menu_volume = 0.6
miss_volume = 0.2
mute_last_second = 0
screwupvol = 0.25
sfx_volume = 0.7
single_track_miss_volume = 0.9
songvol = 0.8
speed_factor = 1.0
stereo = True
whammy_effect = 0

[coffee]
failingenabled = True
game_phrases = 2
hopo_frequency = 2
neckspeed = 100
noterotate = False
song_display_mode = 4
songfilepath = True
themename = MegaLight

[debug]
show_bpm = 0
show_freestyle_active = 0
show_raw_vocal_data = 0
use_new_vbpm_beta = 0
use_unedited_midis = 1

[engine]
highpriority = False

[fretboard]
ovrneckoverlay = True
point_of_view = 5

[game]
accuracy_mode = 2
accuracy_pos = 1
adv_settings = False
base_library = 
bass_groove_enable = 1
bass_groove_neck = 2
bass_kick_sound = False
battle_amp_overload = 1
battle_death_drain = 2
battle_diff_up = 1
battle_double = 1
battle_steal = 1
battle_string_break = 1
battle_switch_controls = 1
battle_tune = 1
battle_whammy = 1
beat_claps = False
bg_neck_alpha = 1.0
big_rock_endings = 2
career_star_min = 3
cheer_loop_delay = 550
congrats = True
control0 = defaultg
control1 = defaultd
control2 = defaultm
control3 = None
decimal_places = 1
default_neck = defaultneck
disable_vbpm = False
drum_navigation = True
drum_sp_mode = 0
fail_neck_alpha = 1.0
frets_under_notes = True
game_mode = 0
game_time = 1
gfx_version_tag = 1
gh2_sloppy = 0
gsolo_acc_pos = 3
gsolo_accuracy_disp = 1
guitar_solo_neck = 2
hopo_after_chord = 1
hopo_debug_disp = 0
hopo_indicator = False
hopo_system = 3
hsmovement = 1
ignore_open_strums = True
in_game_font_shadowing = False
in_game_stars = 1
incoming_neck_mode = 2
joysticks = 1
jurg_logic_p0 = 1
jurg_logic_p1 = 1
jurg_logic_p2 = 1
jurg_logic_p3 = 1
jurg_p0 = False
jurg_p1 = False
jurg_p2 = False
jurg_p3 = False
jurg_skill_p0 = 5
jurg_skill_p1 = 5
jurg_skill_p2 = 5
jurg_skill_p3 = 5
keep_play_count = 1
key_checker_mode = 1
kill_debug = False
language = 
large_drum_neck = False
last_theme = 
log_class_inits = 0
log_ini_reads = 0
log_loadings = 0
log_marker_notes = 0
log_sections = 0
log_starpower_misses = 0
log_undefined_gets = 0
lost_focus_pause = True
lphrases = True
lyric_mode = 2
mark_solo_sections = 1
midi_lyric_mode = 2
miss_pauses_anim = 0
multiplayer_mode = 0
mute_drum_fill = 1
neck_alpha = 1.0
necks_alpha = 1.0
note_hit_window = 2
notedisappear = False
nstype = 2
overlay_neck_alpha = 1.0
p2_menu_nav = 1
partial_stars = 1
party_time = 30
player0 = None
player1 = None
player2 = None
player3 = None
players = 1
preload_labels = False
quickplay_tiers = 1
rb_midi_lyrics = 1
rb_midi_sections = 0
rb_sp_neck_glow = False
result_cheer_loop = 2
resume_countdown = 1
rotate_stages = 0
script_lyric_pos = 0
scroll_delay = 500
scroll_rate = 50
show_unused_text_events = False
small_rb_mult = 1
solo_frame = 1
solo_neck_alpha = 1.0
song_hopo_freq = 1
song_icons = True
song_listing_mode = 0
song_stage = 1
songcovertype = False
songlist_difficulty = 0
songlist_extra_stats = True
songlist_instrument = 0
songlistrotation = True
sort_direction = 0
sort_order = 0
sp_notes_while_active = 2
stage_animate = 0
stage_animate_delay = 3
stage_mode = 0
stage_rotate_delay = 800
star_claps = False
star_scoring = 3
starfx = True
starpower_mode = 2
sustain_muting = 1
t_sound = 2
tut = False
uploadscores = False
uploadurl_w67_starpower = http://www.wembley1967.com/chart/uploadsp.php
use_graphical_submenu = 1
use_new_pitch_analyzer = True
vocal_scroll = 2
vocal_speed = 100
whammy_changes_sort_order = True
whammy_saves_starpower = False

[handicap]
detailed_handicap = 1
early_hit_window = 0

[log]
log_lyric_events = 0
log_tempo_events = 0
log_unedited_midis = 0

[network]
updateinterval = 72

[opengl]
svgshaders = False

[performance]
cache_song_metadata = True
disable_libcount = True
disable_librotation = True
game_priority = 2
in_game_stats = 0
killfx = 0
max_players = 2
star_continuous_fillup = True
star_score_updates = 1
starspin = True
static_strings = True
use_psyco = False

[quickset]
gameplay = 0
performance = 0

[songlist]
nil_show_next_score = 0

[video]
counting = False
disable_fretsfx = False
fps = 80
fullscreen = False
hitglow_color = 0
multisamples = 4
resolution = 640x480
shader_cd = cd
shader_neck = theme
shader_notes = theme
shader_sololight = sololight
shader_stage = theme
shader_tail = tail2
shader_use = True
show_fps = False

**Comment by mdsitton** [comment]
That would be your configuration file: fofix.ini
The log would be called: fofix.log

So it is running, but there is a graphics issue. It sounds like you might have a graphics driver issue. Maybe try updating them if you can?

**Comment by mrknife00** [comment]
in the location that you gave me, just had this file, and my drivers are up-to-date as you can see here:
[http://imgur.com/YLZoQ6D](url) i think its because the game is imcompatible...

**Comment by mdsitton** [comment]
I know its not incompatible because I also run Windows 10 64-bit some of the time, also with an AMD Graphics Card.

One thing i can think of I see you have an intel cpu with integrated graphics. Maybe for some reason its using that instead? Try running the dxdiag tool from your start menu and posting what it shows here.

**Comment by mrknife00** [comment]
Here the screenshots: [http://imgur.com/a/ycm22](url) 
And what fofix version are you using?

**Comment by mdsitton** [comment]
Well i'm a fofix developer so that tends to lean more towards the latest code for 4.0. But i do sometimes bring out 3.121 to test certain things.

One last thing i would try. Try deleting your fofix.ini file and running the game fresh like that, and if it still has issues i'm not sure what else i can do here.

**Comment by mrknife00** [comment]
Worked! but the 1.2.451 version
It worked after a windows update, i don't know why...
Thanks for helping!

**Comment by mdsitton** [comment]
Well FoF has really terrible compatibility with newer songs. FoFiX is better with compatibility but somewhat slower, I don't think your pc should have any issues playing fofix with good performance so you should probably just go with FoFiX.
