### ISSUE TITLE
Don't know the development headers' name

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [fofix/fofix#68]
Sorry, what are the package names for "OpenGL, GLU, GLib, SDL, SDL_mixer, libogg, libvorbisfile, libtheora, libsoundtouch, and libswscale (part of ffmpeg) development headers" on openSUSE?

**Comment by Linkid** [comment]
Hi!
You can find those packages in https://software.opensuse.org and https://en.opensuse.org/openSUSE:Packaging_Games. Furthermore, if you want, you can try to package FoFiX for OpenSuse :). Maybe the last link will help you.

For the record, here are packages I found:
- OpenGL: `opengl-games-utils`
- SDL: `libSDL-1_2-0`, `libSDL_mixer-1_2-0`
