### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by shikulja** [fofix/fofix#69]
1. No such file or directory: 'numpy-atlas.dll'
helps get C:\Python27\Lib\site-packages\numpy\core\numpy-atlas.dll and copied it to the same folder that has the setup.py
2.  not building with py2exe-0.9.2.2.win32 on python 2.7
helps old py2exe-0.6.9.win32-py2.7
3. on x64 not working 7z becose C:\Program Files (x86) folder
4. bad problem not building 7z and sfx
svn wiki not found

when many songs crush when scanning songs. 
.fofix-cache delete, edit .inis not help
[    6.344000] (E) Terminating due to unhandled exception: 
  File "fofix\game\song\song.pyo", line 3397, in updateSongDatabase
  File "fofix\game\song\song.pyo", line 3010, in getAvailableSongs
  File "fofix\game\song\song.pyo", line 264, in __init__
  File "fofix\game\song\song.pyo", line 329, in getScores
TypeError: Non-hexadecimal digit found

**Comment by wrzwicky** [comment]
There are two errors here, you should post them as separate issue reports.

Re. unhandled exception: The problem is not with the quantity of songs you have, but with one song in particular -- the high-score coding for that song is corrupted. You need to find the bad song, then attach the "song.ini" file from it here so we can debug this issue. Afterwards, you should delete the "score" and "scores_ext" lines from inside that file, and the game should then work fine, though you'll lose your high scores for that song.

**Comment by wrzwicky** [comment]
#87 "fixes" both items. Part 1 is fixed, and additionally I finished setup.py so it produces a good distro.  Part 2 is suppressed; there's no way to recover your high scores (unless you post a file and someone finds a workaround) but at least FoFix won't crash anymore.

**Comment by shikulja** [comment]
I deleted some of their songs for which there was an error when scanning songs
scores = 63657265616c310a370a646963740a6c6973740a7475706c650a340a693133353038390a69350a73350a4d696b65797334300a656361363738663366356131333133333064643435653433356566643938623531306634356238617475706c650a340a693132363431330a69340a73350a4d696b65797334300a643531663634623665383636363637366436623461663534656266393962613939366465303138357475706c650a340a6936343136310a69340a73330a6472777334300a313036623036333733396231393034383931363966306165636337633630366466633966343832357475706c650a340a6935373832320a69340a73330a6472777334300a386632373731336664313163656531646636326361666336326333646466613139393435333335637475706c650a340a6934383237370a69340a73330a6472777334300a34663036383232386130383530333864393734653362393639613733663430313132376439326239310a72310a69300a350a72320a72330a72340a72350a72360a72300a
cassettecolor = #a4a5a1


like this crashing on scan
[song]
artist = Misfits
name = Scream!
scores = 

by Lasez


In the game when you run any songs error, I can not compile correctly ..
<spoiler>
[    0.001000] (D) Logging initialized: Sat Oct 14 20:23:05 2017
[    0.117000] (D) GameEngine class init (GameEngine.py)...
[    0.117000] (D) FoFiX v4.0.0 alpha 2 starting up...
[    0.117000] (D) Python version: 2.7.12
[    0.117000] (D) Pygame version: 1.9.1release
[    0.117000] (D) PyOpenGL version: 3.1.0
[    0.117000] (D) Numpy version: 1.11.2
[    0.117000] (D) PIL version: 1.1.7
[    0.117000] (D) sys.argv: ['E:\\FoF 3.1\\FoFiX.exe']
[    0.117000] (D) os.name: nt
[    0.117000] (D) sys.platform: win32
[    0.117000] (D) win32api.GetVersionEx(1): (6, 1, 7601, 2, 'Service Pack 1', 1, 0, 256, 1, 0)
[    0.120000] (D) Disabling screensaver.
[    0.120000] (D) Initializing audio.
[    0.131000] (D) Audio configuration: (44100, -16, 2)
[    0.131000] (D) Initializing video.
[    0.817000] (D) OpenGL version: 4.5.13492 Compatibility Profile Context 22.19.677.257
[    0.817000] (D) OpenGL vendor: ATI Technologies Inc.
[    0.817000] (D) OpenGL renderer: AMD Radeon (TM) R9 380 Series
[    0.817000] (D) OpenGL extensions: GL_AMDX_debug_output GL_AMD_blend_minmax_factor GL_AMD_conservative_depth GL_AMD_debug_output GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_sample_positions GL_AMD_gcn_shader GL_AMD_gpu_shader_half_float GL_AMD_gpu_shader_half_float2 GL_AMD_gpu_shader_int64 GL_AMD_interleaved_elements GL_AMD_multi_draw_indirect GL_AMD_name_gen_delete GL_AMD_occlusion_query_event GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_sample_positions GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_atomic_counter_ops GL_AMD_shader_stencil_export GL_AMD_shader_stencil_value_export GL_AMD_shader_trace GL_AMD_shader_trinary_minmax GL_AMD_sparse_texture GL_AMD_sparse_texture_pool GL_AMD_stencil_operation_extended GL_AMD_texture_cube_map_array GL_AMD_texture_texture4 GL_AMD_transform_feedback3_lines_triangles GL_AMD_transform_feedback4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_snorm GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_envmap_bumpmap GL_ATI_fragment_shader GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_buffer GL_EXT_copy_texture GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_histogram GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texgen_reflection GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_bptc GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_texture_mirrored_repeat GL_INTEL_fragment_shader_ordering GL_KHR_context_flush_control GL_KHR_debug GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_explicit_multisample GL_NV_float_buffer GL_NV_half_float GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_OES_EGL_image GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint WGL_EXT_swap_control
[    0.823000] (D) Compiling shader "stage" from E:\FoF 3.1\data\shaders\lightning.vert and E:\FoF 3.1\data\shaders\lightning.frag.
[    0.827000] (D) Compiling shader "sololight" from E:\FoF 3.1\data\shaders\lightning.vert and E:\FoF 3.1\data\shaders\lightning.frag.
[    0.828000] (D) Compiling shader "tail" from E:\FoF 3.1\data\shaders\lightning.vert and E:\FoF 3.1\data\shaders\lightning.frag.
[    0.830000] (D) Compiling shader "tail2" from E:\FoF 3.1\data\shaders\rockbandtail.vert and E:\FoF 3.1\data\shaders\rockbandtail.frag.
[    0.831000] (D) Compiling shader "notes" from E:\FoF 3.1\data\shaders\metal.vert and E:\FoF 3.1\data\shaders\metal.frag.
[    0.832000] (D) Compiling shader "neck" from E:\FoF 3.1\data\shaders\neck.vert and E:\FoF 3.1\data\shaders\neck.frag.
[    0.833000] (D) Compiling shader "cd" from E:\FoF 3.1\data\shaders\cd.vert and E:\FoF 3.1\data\shaders\cd.frag.
[    0.847000] (D) 0 joysticks found.
[    0.847000] (N) MIDI input support is not available; install at least pygame 1.9 to get it.
[    0.861000] (E) Image not found: themes\MegaLight V4\common\guitar.png
[    0.861000] (E) Image not found: themes\MegaLight V4\common\rhythm.png
[    0.861000] (E) Image not found: themes\MegaLight V4\common\bass.png
[    0.862000] (E) Image not found: themes\MegaLight V4\common\lead.png
[    0.862000] (E) Image not found: themes\MegaLight V4\common\drum.png
[    0.862000] (E) Image not found: themes\MegaLight V4\common\vocal.png
[    1.059000] (D) Theme font not found: title.ttf
[    1.060000] (D) Theme font not found: streak.ttf
[    1.060000] (D) Theme font not found: song.ttf
[    1.061000] (D) Theme font not found: songlist.ttf
[    1.061000] (D) Theme font not found: songlist.ttf
[    1.061000] (D) Theme font not found: streakphrase.ttf
[    1.064000] (D) guitscw1.ogg - guitscw6.ogg found in sounds
[    1.064000] (D) Theme sound not found: bassdrum.ogg
[    1.065000] (W) File battleused.ogg not found using default instead.
[    1.065000] (D) Theme sound not found: crash.ogg
[    1.065000] (D) Theme sound not found: clapsound.ogg
[    1.066000] (W) File coopfail.ogg not found using default instead.
[    1.066000] (D) Theme sound not found: failsound.ogg
[    1.066000] (W) File rescue.ogg not found using default instead.
[    1.067000] (D) Theme sound not found: rocksound.ogg
[    1.067000] (W) File staractivate.ogg not found using default instead.
[    1.068000] (W) File stardeactivate.ogg not found using default instead.
[    1.068000] (D) Theme sound not found: starding.ogg
[    1.069000] (D) Theme sound not found: starlost.ogg
[    1.069000] (W) File starpowerready.ogg not found using default instead.
[    1.070000] (D) Theme sound not found: tom01.ogg
[    1.070000] (D) Theme sound not found: tom02.ogg
[    1.071000] (D) Theme sound not found: tom03.ogg
[    1.071000] (W) MegaLight V4/sounds/crowdcheers.ogg not found -- using data/sounds/crowdcheers.ogg instead.
[    1.071000] (D) Default animated stage for MegaLight V4 theme = Normal
[    1.072000] (D) theme.ini loaded
[    1.073000] (D) bassscw1.ogg - bassscw6.ogg found in sounds
[    1.074000] (D) Ready.
[    1.081000] (D) drumscw1.ogg - drumscw8.ogg found in sounds
[    1.092000] (D) accept1.ogg - accept1.ogg found in themes\MegaLight V4\sounds
[    1.096000] (D) back1.ogg - back1.ogg found in themes\MegaLight V4\sounds
[    1.711000] (D) View: Push: MainMenu
[    1.711000] (D) View: Push: Menu
[    1.711000] (E) Config key theme.shader_neck not defined while reading C:\Users\User\AppData\Roaming\fofix\fofix.ini.
Traceback (most recent call last):
  File "fofix\core\Config.pyo", line 195, in get
KeyError: 'shader_neck'

[    1.711000] (E) Config key theme.shader_notes not defined while reading C:\Users\User\AppData\Roaming\fofix\fofix.ini.
Traceback (most recent call last):
  File "fofix\core\Config.pyo", line 195, in get
KeyError: 'shader_notes'

[    1.711000] (E) Config key video.shader_tail2 not defined while reading C:\Users\User\AppData\Roaming\fofix\fofix.ini.
Traceback (most recent call last):
  File "fofix\core\Config.pyo", line 195, in get
KeyError: 'shader_tail2'

[    1.711000] (E) Config key theme.shader_stage not defined while reading C:\Users\User\AppData\Roaming\fofix\fofix.ini.
Traceback (most recent call last):
  File "fofix\core\Config.pyo", line 195, in get
KeyError: 'shader_stage'

[    2.148000] (W) Your theme does not appear to properly support the solo graphical submenu. Check to be sure you have the latest version of your theme.
[    2.148000] (D) View: Push: Menu
[    2.398000] (D) View: Pop all
[    2.398000] (D) View: Pop: MainMenu
[    2.398000] (D) View: Pop: Menu
[    2.398000] (D) View: Pop: Menu
[    2.398000] (D) View: Pop: MainMenu
[    2.415000] (D) View: Pop: Menu
[    2.432000] (E) Image not found: users\players\Sergey.png
[    2.432000] (E) Image not found: users\players\Sergey.png
[    2.432000] (E) Image not found: users\players\Sergey.png
[    2.432000] (E) Image not found: users\players\Sergey.png
[    2.433000] (D) View: Push: Lobby
[    2.433000] (W) No theme class for themeLobby - Loading default...
[    2.433000] (E) Image not found: users\players\Sergey.png
[    2.433000] (E) Image not found: users\players\Sergey.png
[    2.433000] (E) Image not found: users\players\Sergey.png
[    2.433000] (E) Image not found: users\players\Sergey.png
[    2.973000] (D) Updating song cache.
[    3.032000] (D) View: Push: LoadingSplashScreen
{Big list songs}
[    9.660000] (D) View: Pop: LoadingSplashScreen
[    9.660000] (D) View: Push: LoadingSplashScreen
[    9.677000] (W) No theme class for setlist - Loading default...
[    9.678000] (W) Your theme does not appear to properly support the setlist graphical submenu. Check to be sure you have the latest version of your theme.
[    9.678000] (D) Loading libraries in songs\Machinae Supremacy
[    9.695000] (D) Song.getAvailableLibraries function call...library = songs\Machinae Supremacy
[    9.695000] (D) Loading songs in songs\Machinae Supremacy
[    9.697000] (D) Song E:\FoF 3.1\data\songs\Machinae Supremacy\Machinae Supremacy - Great Gianna Sisters\song.ini successfully loaded from cache.
[    9.697000] (D) Song E:\FoF 3.1\data\songs\Machinae Supremacy\Machinae Supremacy - Rise\song.ini successfully loaded from cache.
[    9.710000] (D) Setlist loaded.
[    9.712000] (D) View: Pop: LoadingSplashScreen
[    9.712000] (W) Unable to load image file: E:\FoF 3.1\data\themes\MegaLight V4\setlist\item.dae
[    9.712000] (W) Unable to load image file: E:\FoF 3.1\data\themes\MegaLight V4\setlist\label.dae
[    9.713000] (W) Unable to load image file: E:\FoF 3.1\data\themes\MegaLight V4\setlist\library.dae
[    9.713000] (W) Unable to load image file: E:\FoF 3.1\data\themes\MegaLight V4\setlist\library_label.dae
[    9.742000] (D) View: Push: SongChoosingScene
[    9.742000] (D) View: Pop: Lobby
[   13.492000] (D) Song E:\FoF 3.1\data\songs\Machinae Supremacy\Machinae Supremacy - Rise\song.ini successfully loaded from cache.
[   13.492000] (D) Song E:\FoF 3.1\data\songs\Machinae Supremacy\Machinae Supremacy - Rise\song.ini successfully loaded from cache.
[   13.504000] (D) View: Push: PartDiffChooser
[   13.504000] (W) No theme class for partDiff - Loading default...
[   16.152000] (D) View: Pop: PartDiffChooser
[   16.172000] (D) View: Pop: SongChoosingScene
[   16.175000] (D) BandPlayBaseScene init...
[   16.176000] (D) Song E:\FoF 3.1\data\songs\Machinae Supremacy\Machinae Supremacy - Rise\song.ini successfully loaded from cache.
[   16.176000] (D) View: Push: SongLoadingSplashScreen
[   16.209000] (D) GuitarScene init...
[   16.210000] (E) Attempted to load theme variable fret_press - no default found.
Traceback (most recent call last):
  File "fofix\core\Theme.pyo", line 107, in __getattr__
KeyError: 'fret_press'

[   16.228000] (D) Image not found: themes\MegaLight V4\notes/star.dae
[   16.537000] (D) Image not found: themes\MegaLight V4\notes/staratex_a.png
[   16.539000] (D) Image not found: themes\MegaLight V4\tails/tail0.png
[   16.539000] (D) Simple tails used; complex tail loading error...
[   16.553000] (D) Image not found: themes\MegaLight V4\flames/hitflames1.png
[   16.560000] (D) Image not found: themes\MegaLight V4\flames/hitflamesanimation.png
[   16.560000] (D) Image not found: themes\MegaLight V4\flames/powerhitflamesanimation.png
[   16.561000] (D) Image not found: themes\MegaLight V4\flames/hitglowanimation.png
[   16.561000] (D) Image not found: themes\MegaLight V4\flames/hitglow.png
[   16.561000] (D) Image not found: themes\MegaLight V4\flames/hitglow2.png
[   16.562000] (E) Attempted to load theme variable boardFade - no default found.
Traceback (most recent call last):
  File "fofix\core\Theme.pyo", line 107, in __getattr__
KeyError: 'boardFade'

[   16.577000] (D) GuitarScene keysList: [[64, 256, 1024, 4096, 16384, 128, 512, 2048, 8192, 32768]]
[   16.595000] (D) loadSong function call (song.py)...
[   16.595000] (E) Terminating due to unhandled exception: 
Traceback (most recent call last):
  File "FoFiX.py", line 312, in <module>
  File "FoFiX.py", line 294, in run
  File "fofix\core\GameEngine.pyo", line 600, in run
  File "fofix\core\GameEngine.pyo", line 582, in main
  File "fretwork\task.pyo", line 114, in run
  File "fretwork\task.pyo", line 89, in runTask
  File "fofix\core\Input.pyo", line 319, in run
  File "fofix\core\Input.pyo", line 230, in broadcastEvent
  File "fofix\game\SongChoosingScene.pyo", line 843, in keyPressed
  File "fofix\game\SongChoosingScene.pyo", line 631, in startGame
  File "fofix\game\World.pyo", line 124, in createScene
  File "fofix\core\SceneFactory.pyo", line 36, in create
  File "fofix\game\guitarscene\GuitarScene.pyo", line 1209, in __init__
  File "fofix\core\Resource.pyo", line 239, in load
  File "fofix\core\Resource.pyo", line 114, in load
  File "fofix\game\guitarscene\GuitarScene.pyo", line 1209, in <lambda>
  File "fofix\game\song\song.pyo", line 2841, in loadSong
WindowsError: [Error 3] : 'songs\\Machinae Supremacy\\Machinae Supremacy - Rise\\'

</spoiler>


the .ini parser would be fine to modify. Ignore unnecessary entries and correct incorrect parameters.

**Comment by wrzwicky** [comment]
@shikulja Yikes, lots of things going on here.
1. What you have as "FoFiX v4.0.0 alpha 2" does not match what github has under v4.0.0alpha2, so I can't easily trace the problem. I don't have a good solution; someone really needs to make an alpha3 available (preferably with all my fixes included. :)
2. "KeyError: 'shader_stage'" and similar -- These are not problems; the game is simply noting deficiencies in your chosen theme, but is continuing to run.
3. "Your theme does not appear to properly support the solo graphical submenu." -- This appears to be a real problem. When I get these, the game continues to run but exhibits strange problems. Try the other themes and see if anything changes. "MegaLight v4" is the current best theme, though I don't know the best back in alpha2.
4. "WindowsError: [Error 3]" -- Google says this means a file is not found. Make sure those folders exist, and that they don't have strange characters in the name. Check the files in that dir to ensure the ones that FOFIX needs exist and contain something.

**Comment by shikulja** [comment]
thanks for the help, as I wrote, there are no big problems in the new commit, unless with some songs .. something with mid files, eof editor helps; and with themes, mega light really like it, but sometimes it crashes.
The win instruction is incomplete, and the wiki is still not fixed in the create installer
buildPackageWin.cmd need delete 
svn export http://fofix.googlecode.com/svn/wiki wiki
and add wiki folder to repo
I give a link to the broken old version just in case.
(called alpha 2 because the last public version was 4.0 alpha 1 .. it was necessary to give the version number above for a newer version)

https://drive.google.com/file/d/0B6Bbbdpi5BzBVnY1Q2Q1NXZSWFk/view?usp=sharing

**Comment by Linkid** [comment]
Hi.
Thank you for your issue.

About the googlecode link: you should use the git repo (here on GitHub) instead. The SVN one is old and deprecated, just like the wiki (which I deleted on GitHub).

About the version: as it was said before, you should use the master version. The alpha 2 is… an alpha version (with some bugs already fixed, though) ;).

Thank you again.
