### ISSUE TITLE
Windows Dependency Pack does not contains all depencies

### ISSUE THREAD

**Issue by samusaran** [fofix/fofix#81]
Closed issue #75 reintroduced #56.
The google code archive does not contains ogg.lib, so that at the actual state, anyone with that package is unable to compile the game succefully.

**Comment by wrzwicky** [comment]
Dependency pack appears to be missing:
- glib-2.0.lib
- swscale.lib
- intl.lib
- theoradec.lib
- ogg.lib

I found replacements via Google (attached as zip file; unzip to win32/deps/lib) and it now builds, but game will not run. Error is:
- ImportError: DLL load failed: The operating system cannot run %1.
I don't know what's wrong, though I suspect my lib files do not match your dll files.

Note your documentation has many links to deppack zips all over the internet. I don't see the missing lib files in any of them.
- fofix/blob/master/doc/source/quickstart/installation.rst links to dropboxusercontent.com
- fofix/wiki/Running-From-Sources links to two files on mediafire.com
- fofix/fofix/README.md links to google-code-archive-downloads

Is there any reason you can't just check those files into github right here?

[**Attachment**] Replacment libs: [lib.zip](https://github.com/fofix/fofix/files/1295734/lib.zip)

**Comment by Linkid** [comment]
Ok, you should take a look to #82 ;).

About the 3 links:
- the doc and the README will be updated with #82.
- the wiki is outdated will be removed as soon as possible ;).
